{
 "title": "Nimiq3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Base stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synced",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_consensus_is_established", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest batch number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_watchdog_current_batch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peers connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_network_peer_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nimiq_staking_active_validators",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"node-exporter:9100\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_validator_activated{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Activation attempts",
   "type": "stat",
   "description": "Attempts of activation",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nimiq_validator_activated_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart attempts",
   "type": "stat",
   "description": "Restarted by watchdog",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nimiq_watchdog_container_restarts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Jailed",
   "type": "stat",
   "description": "If Jailed takes 8 epochs to be able to reactivate!",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_validator_jailed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest block number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_blockchain_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_watchdog_current_epoch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"node-exporter:9100\"} - node_boot_time_seconds{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator address",
   "type": "stat",
   "description": "Validator address",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_validator_activated{}", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_watchdog_current_health", "legendFormat": "__auto" }
   ]
  },
  { "title": "Validator stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Validator active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_validator_activated", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validator wallet balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nimiq_validator_balance / 100000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Current stakers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_validator_num_stakers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validator stake",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nimiq_validator_stake_balance_luna / 100000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Jailed",
   "type": "stat",
   "description": "If Jailed takes 8 epochs to be able to reactivate!",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_validator_jailed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Balance history",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "nimiq_validator_balance / 100000",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "Stakers History",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 8, "y": 12 },
   "targets": [
    { "expr": "nimiq_validator_num_stakers", "legendFormat": "Stakers history" }
   ]
  },
  {
   "title": "Stake history",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "nimiq_validator_stake_balance_luna / 100000",
     "legendFormat": "Stake history"
    }
   ]
  },
  {
   "title": "Validator Retired",
   "type": "stat",
   "description": "If Jailed takes 8 epochs to be able to reactivate!",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_validator_retired", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reactivation counter",
   "type": "stat",
   "description": "How many times reactivated",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nimiq_validator_reactivated_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block number jailed from.",
   "type": "stat",
   "description": "If Jailed takes 8 epochs to be able to reactivate!",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_validator_jailed_from", "legendFormat": "__auto" }
   ]
  },
  { "title": "Nimiq Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Blockheight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    { "expr": "nimiq_blockchain_block_number", "legendFormat": "Blockheight" }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    { "expr": "nimiq_network_peer_count", "legendFormat": "Peer Count" }
   ]
  },
  {
   "title": "Accounts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "targets": [
    { "expr": "nimiq_accounts_trie_accounts", "legendFormat": "Accounts" }
   ]
  },
  {
   "title": "Mempool TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "targets": [
    { "expr": "nimiq_mempool_tx_count", "legendFormat": "Mempool tx" }
   ]
  },
  { "title": "Container crashing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Restarted containers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(container_name) (docker_container_stop_restart_count)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Crashloop container",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(container_name) (docker_container_crashloop_count)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Restarted containers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "docker_container_stop_restart_count",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Crashloop container",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 41 },
   "targets": [
    {
     "expr": "docker_container_crashloop_count > 1",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Nimiq logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 15, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "{container_name=\"/node\"}"
    }
   ]
  },
  {
   "title": "Validator Activator logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 53 },
   "targets": [
    {
     "expr": "{container_name=\"/activate_validator\"}",
     "maxLines": 500
    }
   ]
  },
  {
   "title": "Watchdog logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 64 },
   "targets": [
    {
     "expr": "{container_name=\"/nimiq-watchdog\"}",
     "maxLines": 500
    }
   ]
  }
 ]
}